services:
  # ---------- Base de datos ----------
  db:
    image: mariadb:10.6
    container_name: acme-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: acmeroot
      MARIADB_DATABASE: acme

    volumes:
      - db_data:/var/lib/mysql
      - ./Backend/database/acme.sql:/docker-entrypoint-initdb.d/acme.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 12

  # ---------- Backend (API) ----------
  backend:
    build: ./Backend
    container_name: acme-backend
    restart: unless-stopped
    environment:
      PORT: 3000
      DB_HOST: db 
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: acmeroot
      DB_NAME: acme
      JWT_SECRET: acme-secret-key-cambiar-en-produccion
      
      GOOGLE_CLIENT_ID: "930384574426-dh3urq7l2h4ldnk4djhmiqg7ccfbvc40.apps.googleusercontent.com"

      # ---- Envío de Email (Nodemailer + Gmail OAuth2) ----
      EMAIL_USER: "${EMAIL_USER:-}"
      EMAIL_CLIENT_ID: "${EMAIL_CLIENT_ID:-}"
      EMAIL_CLIENT_SECRET: "${EMAIL_CLIENT_SECRET:-}"
      EMAIL_REDIRECT_URI: "https://developers.google.com/oauthplayground"
      EMAIL_REFRESH_TOKEN: "${EMAIL_REFRESH_TOKEN:-}"
      # URL pública del frontend (para el enlace de recuperación de contraseña).
      FRONTEND_URL: "http://pacheco.chillan.ubiobio.cl:8075"
    ports:
      - "8076:3000"
    depends_on:
      db:
        condition: service_healthy

  # ---------- Frontend ----------
  frontend:
    build: ./Frontend
    container_name: acme-frontend
    restart: unless-stopped
    ports:
      - "8075:80"
    depends_on:
      - backend

volumes:
  db_data:
